version: '3'

services:
  dicecat:
    image: starlitghost/dicecat
    container_name: dicecat 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
    restart: unless-stopped

# vim: tabstop=2 shiftwidth=2 expandtab
